# Build and Task Haskell Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.8.2

      - name: Install dependencies
        run: |
          cabal update
          cabal install --only-dependencies

      - name: Build
        run: cabal build

      - name: Run tests
        run: cabal test
